### ISSUE TITLE
The Excel Add-in is not installing with a CDP-IME installer for 64 bits Excel 

### ISSUE THREAD

**Issue by oiynick** [RHEAGROUP/CDP4-IME-Community-Edition#4] opened 2018-03-21 07:50 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

MSI Installer does not install CDP4 Excel Add-in with different parameters (had an opportunity to try different options of installation: Custom, selecting only Add-In or selecting everything, Complete and Typical). 

### Steps to Reproduce

Nothing tried yet.

### System Configuration

Web Services - Ubuntu 16.04.4 LTS, Postgres 9.6, Windows different versions.

- CDP4 version:
  - [ ] CDP4-IME: 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5
- Web Services:
  - [ ] CDP4 Web Services version: 1.0.0
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 64 bit
  - [ ] Windows OS (32/64 bit): Windows 10 64 bit, Windows 8 64 bit.
  - [ ] Additional information: Tried 3 different computers with different versions of CDP4-IME.

**Comment by samatrhea** [comment] 2018-03-21 09:04
Some questions:
- what language of Windows and Excel are you using?
- in the installation directory, are the following files present: **CDP4AddinCE.dll** and **CDP4AddinCE.tlb**
- in the registry, is the following key present **Computer\HKEY_CURRENT_USER\Software\Microsoft\Office\Excel\AddIns\CDP4EE.Addin** and is the **LoadBehavior" set to 3

**Comment by oiynick** [comment] 2018-03-21 09:56
Hello, 
Thank you very much for the quick reply. Answering your questions I can say:

- The languages of OS and Excel were used both Russian and English
- Both .dll and .tlb files are presented in */Program Files/RHEA/CDP4-CE/bin/
- **No such entry in register is presented on!**

**Comment by samatrhea** [comment] 2018-03-21 11:25
The installer should have installed the registry key, as you can see in the [wix installer](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/blob/master/CDP4IMEInstaller/CDP4Addin.wxs)

the following key needs to be installed:

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Office\Excel\AddIns\CDP4CE.Addin]
"LoadBehavior"=dword:00000003
"FriendlyName"="CDP4-CE Office Add-in"
"Description"="The CDP4-CE Office Add-in provides CDP4 application integration with Microsoft Office Suite"
```

You can try to add this manually while we investigate further what the issue may be. I run CDP4CE addin successfully on win10 64 bit, but my office version is 32 bit. But, that should not be a problem.

**Comment by oiynick** [comment] 2018-03-21 12:01
Dear Sam,

The installation of the new registry key didn't help as well.
The following steps were completed:

1. Bringing a new key to the register 
2. Inserting a new values 
3. Rebooting
4. Check

Unfortunately the add in hasn't appeared.

**Comment by oiynick** [comment] 2018-03-21 16:40
Dear Sam,

I figured out the problem roots. The add-in actually doesn't work on x64 Office versions at all (I've tried at least 6 different machines with x64 Office pack) it worked pretty well on machines with x86 Office pack.

It'd be great to have a working x64 add-in as well in future.
Thank you for help.

**Comment by samatrhea** [comment] 2018-03-21 21:15
we'll work on that ASAP. Thanks for the analysis and finding the root cause.

**Comment by samatrhea** [comment] 2018-03-27 07:18
It seems that wix installers are for a specific platform. The following resources explain how to make a 32 and 64 bit build.

http://wixtoolset.org/documentation/manual/v3/xsd/wix/package.html
http://wixtoolset.org/documentation/manual/v3/msbuild/task_reference/candle.html
http://www.4tecture.ch/blog/wix-toolset-multi-targeting-with-a-single-project

**Comment by oiynick** [comment] 2018-03-27 07:27
Dear Sam,

Thank you very much! I will study that carefully!

**Comment by samatrhea** [comment] 2018-03-27 07:35
Hi,

Nice to know you want to contribute, i've already assigned the task to myself and i am working on it as we speak. Please not that if you want to contribute to the code, you have to get the CLA signed. 

https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/wiki/CLA

Ciao, Sam

**Comment by samatrhea** [comment] 2018-03-27 07:55
some more links that can be useful: https://blogs.msdn.microsoft.com/astebner/2007/08/10/example-wix-based-setup-that-can-be-used-to-build-both-32-bit-and-64-bit-msis/

**Comment by samatrhea** [comment] 2018-03-27 17:07
We have updated the installer project to cope with 32 and 64 bit systems. We have verified that the CDP4-CE Excel add-in now also works on windows 64 bit and Excel 64 bit. We plan to make a new release of the CDP4-CE this week with other new exciting features. Once that is landed on master and released this ticket will auto-close.

@oiynick let us know how it behaves on your systems.

**Comment by oiynick** [comment] 2018-03-28 06:32
Dear Sam,
 
Thank you very much for the quick support. The compiled wix-installer is perfectly work now on the Windows x64 with Office x64, as well as Windows x32 with Office x64.

Can't wait for the next release to come!
Have a great day!

Best regards.

**Closed** 2018-03-29 06:13 UTC
Labels: bug
