### ISSUE TITLE
Crossview editor - formatting not completed on sheet generation when only a single boolean parameter is selected

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#677] opened 2021-01-11 16:13 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Crossview editor - formatting not completed on sheet generation when only a single boolean parameter is selected. The resulting sheet shows grid lines:

![image](https://user-images.githubusercontent.com/35371313/104206486-de050880-542f-11eb-8bbc-e65bfc8180f6.png)

very specific testing case, so no problem in any normal (operational) situation most likely, formatting is applied normally when multiple parameters are selected.

### Steps to Reproduce

* open model that contains boolean parameter type
* for crossview editor, select (an) element definition(s) and then as parameter type only the boolean parameter type
* generate sheet

sheet is now generated with visible grid lines

### Logs

  - [x] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 6.0.0 RC7
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by cozminvelciu** [comment] 2021-01-18 13:46
Found this to be caused by the same error described in #693. The problem seems to be independent of the ParameterType, and only happens when trying to generate a Crossview with a single ParameterType.

**Comment by cozminvelciu** [comment] 2021-01-19 05:04
Fixed by #693.

**Closed by cozminvelciu** 2021-01-19 05:04 UTC
Labels: 0.5sp, Crossview, trivial
