### ISSUE TITLE
Error - object reference not set to an instance of an object

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#164] opened 2019-06-25 11:17 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When working on customer server, encountered problem after some time. Performed various actions on various models, mainly editing relationships and editing/creating domains of expertise.

Actions not continuous, included locking screen and continuing at later time (without disconnecting).

At one point, received the following error:
Error - object reference not set to an instance of an object

Not possible anymore to perform various attempted actions, e.g. editing items, opening model, refreshing.
After disconnecting and reconnecting, able to continue working.

Problem occured multiple times however today while working. Log files of 1 specific example case available on request.

### Logs

  - [ ] I have attached a log file or included the relevant section in this issue  >Log files of 1 specific example case available on request.
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 4.0.1

  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment] 2019-06-25 12:21
it seems like this bug has been introduced in version 4.0.0, we will investigate

**Comment by samatrhea** [comment] 2019-06-25 12:22
@MartinFijneman can you attach the log file please, it seems to be missing

**Comment by samatrhea** [comment] 2019-06-25 12:50
[20190625 1300 CDP4IME BU Error object reference not set to an instance of an object.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/3325321/20190625.1300.CDP4IME.BU.Error.object.reference.not.set.to.an.instance.of.an.object.log)
[20190625 1303 CDP4IME object reference not set to an instance of an object.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/3325322/20190625.1303.CDP4IME.object.reference.not.set.to.an.instance.of.an.object.log)

**Comment by MartinFijneman** [comment] 2019-06-25 12:51
unclear what may be causing it, but in 3 cases had this problem this morning. For one of these cases, I think I was trying to open an engineering model. For the others I don't know/remember what the exact action was prior to the error

After getting this error, no other actions seemed to be possible in the UI, reload also not working, had to disconnect from server.

**Comment by samatrhea** [comment] 2019-06-25 12:52
@MartinFijneman can you revert to the last version of version 3.x.y.z? and let us know whether this issue is still present?

**Comment by MartinFijneman** [comment] 2019-06-25 13:00
Summary of main actions performed on model:
* opening and closing various engineering models
* edited relationship categories (so changing category for existing relationships in an engineering model

Not sure if the following actions were done before the errors already, or only after the latest error (3rd), but given for completeness:
* add new domains of expertise
* set 1 domain of expertise to "deprecated"
* edited a domain of expertise (being used in engineering models)
* editing domains of expertise in engineering models
* assigning participants

**Comment by alexatrhea** [comment] 2019-10-23 10:28
@MartinFijneman even with provided logs it is impossible to track down this error. Only perhaps a dev can debug while connected to the server in question. If this is possible, please provide serve details to a dev in private. If not possible, issue will be closed until a reproducible diagnosis can be made.

**Comment by alexatrhea** [comment] 2019-10-31 10:45
Closing as can't reproduce. Refile the issue if come across again.

**Closed by alexatrhea** 2019-10-31 10:45 UTC
Labels: bug, can't reproduce, major
