### ISSUE TITLE
"Concurrent Design Team Member" is inactive person role

### ISSUE THREAD

**Issue by oiynick** [RHEAGROUP/CDP4-IME-Community-Edition#25] opened 2018-06-20 09:22 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The concurrent design team member has no even READ access to the Engineering model, where he is presented. However the iteration role access parameter is set to "READ".

### Steps to Reproduce
Create a person in the engineering model with a "Concurrent Design Team Member" role, add this person to the Engineering Model, log in using recently created account, hit the "Open" button.

### Logs

  - [ ] There are no logs regarding the issue
  - [x] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 1.0.13 
  - [x] Other: The bug has also been there on the 1.0.7 and 1.0.8 CDP4-IME versions
  
- Web Services:
  - [x] CDP4 Web Services version: 1.0.1 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [x] Windows OS (32/64 bit): All Windows 8 versions, x64; Windows 10 Pro, x64
  - [ ] Additional information:

**Comment by samatrhea** [comment] 2018-06-20 14:12
This seems to be a duplicate of https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues/11

**Comment by samatrhea** [comment] 2018-06-22 15:14
Issue on Web Services [11](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues/11) closed

**Closed by samatrhea** 2018-06-22 15:14 UTC
Labels: duplicate
