### ISSUE TITLE
specialized quatityKind parameters loose scale when making option- or state-dependent

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#3] opened 2018-01-22 11:18 UTC
testing on public server, at one point in the test I couldn't submit a value for parameters "dry mass" and "wet mass" from the system domain, gave error about scale being null.

In any case reproducible with parameter "dry mass" in new testing activity: problem is reproducible and occurs more specifically when these specialized parameters are made option- and/or state-dependent.

After making it option- or state-dependent and then rebuilding the parameter sheet, the scale indication is not available on the sheet for these specialized parameters.

So when setting this dependency, the scale is somehow not taken over for each value set.

The manual value column in excel then seems to be treated as text instead of a number (content outlined left instead of right), and trying to submit leads to an error message.

![image](https://user-images.githubusercontent.com/35371313/35218305-6912bbbc-ff6e-11e7-928f-af891ec30fe1.png)

**Comment by samatrhea** [comment] 2018-01-23 23:46
When a Parameter is edited that references a ParameterType of SpecializedQuantityKind the scales combox is not populated and the view-model `SelectedScale`  property is null. When the Parameter is edited then the result is that the selected scale is set to null. This causes problems in the generation of the parameter sheet. The problem is not in the sheet generation, but in the edit view-model of a Parameter.

It seems the CDP4Services allow a Parameter that references a ParameterType of QuantityKind's scale set to null. According to 10-25 this should not be allowed, this is reported [here](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues/1)

**Comment by samatrhea** [comment] 2018-02-18 16:12
fixed in 98ecd849a51f8835e603fa5f9efe58745fab23fc

**Closed by samatrhea** 2018-02-18 16:12 UTC
Labels: bug
